### ISSUE TITLE
Responsive - text isn't big enough to be visible on a smartphone

### ISSUE THREAD

**Issue by terichadbourne** [terichadbourne/toilet-transcripts#36]
When you change the width of a browser window on a MacBook, the media queries break at the right point for what makes sense for the content, and the fonts get a little bit smaller but are still very legible as I shrink the window width.  Also good on an iPad. 

When I open the site on a phone (iPhone SE is the one I've tried), though, the text is miniscule and illegible. Is this because the resolution is superior on a phone and there are 10 gazillion pixels across the screen? Do I have to make the font sizes *bigger* on a phone than on a laptop?

**Comment by gr2m** [comment]
the problem is that by default, phones show websites with a width of 980px (or sth similar) to make most pages work, even if they lack any responsive measurements. 

You can tell mobile browsers to use their native width instead by adding this to the `<head>..</head>` on each HTML page:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

See https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by terichadbourne** [comment]
Thanks, @gr2m !! Will give this a try.
